baseURL = 'http://hanhuibao.com/'
languageCode = 'en-us'
title = 'Hanhui Bao'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "Hanhui Bao"
subtitle = "Welcome, I'm an incoming Ph.D. student at University of Tennessee, Knoxville!"
imageUrl = "hugo-demo.jpeg"
imageTitle = "Hanhui Bao"
imageWidth = 300
imageHeight = 400

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Posts'
  pageRef = '/Posts'
  weight = 50
[[menu.main]]
  name = 'CV'
  pageRef = '/CV'
  weight = 40
  url = "CV.pdf"
[[menu.main]]
  name = 'Publications'
  pageRef = '/publications.html'
  weight = 30
[[menu.main]]
  name = 'About'
  pageRef = '/aboutme.html'
  weight = 20

[params.buttons]
-name = "Archive"
url = "/archive/"

[params.cover]
linkFullImages = true

[params]
description = "Hanhui Bao's homepage"